# Generated by Django 3.1.7 on 2021-02-19 20:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя', models.CharField(max_length=100)),
                ('Дата рождения', models.DateField(default=datetime.date.today)),
                ('Описание', models.TextField()),
                ('Изображение', models.ImageField(upload_to='actors/')),
            ],
            options={
                'verbose_name': 'Актёры и режиссеры',
                'verbose_name_plural': 'Актёры и режиссеры',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Категория', models.CharField(max_length=150)),
                ('Описание', models.TextField()),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя', models.CharField(max_length=100)),
                ('Описание', models.TextField()),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Фильм', models.CharField(max_length=100)),
                ('Слоган', models.CharField(default='', max_length=100)),
                ('Описание', models.TextField()),
                ('Постер', models.ImageField(upload_to='movies/')),
                ('Дата выхода', models.PositiveSmallIntegerField(default=2021)),
                ('Страна', models.CharField(max_length=40)),
                ('Премьера в мире', models.DateField(default=datetime.date.today)),
                ('Бюджет', models.PositiveIntegerField(default=0, help_text='Указывать сумму в доллорах')),
                ('Сборы в США', models.PositiveIntegerField(default=0, help_text='Указывать сумму в доллорах')),
                ('Сборы в Мире', models.PositiveIntegerField(default=0, help_text='Указывать сумму в доллорах')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('Черновик', models.BooleanField(default=False)),
                ('actors', models.ManyToManyField(related_name='film_actors', to='movie.Actor', verbose_name='актеры')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.category', verbose_name='Категория')),
                ('genres', models.ManyToManyField(to='movie.Genre', verbose_name='жанры')),
                ('producers', models.ManyToManyField(related_name='film_producer', to='movie.Actor', verbose_name='режиссер')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Значение', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Имя', models.CharField(max_length=100)),
                ('Сообщение', models.TextField(max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP адресс', models.CharField(max_length=15)),
                ('movie', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='movie.movie', verbose_name='фильм')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.ratingstar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Заголовок', models.CharField(max_length=100)),
                ('Описание', models.TextField()),
                ('Изображение', models.ImageField(upload_to='movie_shots/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Кадр из фильма',
                'verbose_name_plural': 'Кадры из фильма',
            },
        ),
    ]
